# Generated by Django 4.2.30 on 2026-07-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DigitalSignature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userkey',
            name='key_name',
            field=models.CharField(default='RSA-2048 Keypair', max_length=100),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='private_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
