# Generated by Django 4.2.11 on 2026-03-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_rename_project_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='github_link',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='live_link',
            new_name='live_url',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='tech_stack',
            new_name='technologies',
        ),
    ]
