# Generated by Django 6.0.3 on 2026-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_technology_remove_projects_technologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='android_release',
            field=models.FileField(blank=True, null=True, upload_to='releases/android/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='linux_release',
            field=models.FileField(blank=True, null=True, upload_to='releases/linux/'),
        ),
    ]
