# Generated by Django 6.0.3 on 2026-03-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_projects_android_release_projects_linux_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='android_release',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='linux_release',
        ),
        migrations.AddField(
            model_name='projects',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
